import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,Check,ChevronRight,ChevronLeft,Scan,Search,FolderOpen,Focus,MousePointer2,Camera,ShieldCheck,Volume2,VolumeX,X,Target,Fingerprint,ArrowRight,RotateCcw,Lock,CheckCircle2} from 'lucide-react';
import {cases,categories,observe,evaluate,toolNames,type Tool,type Evidence} from './engine';
import './style.css';
const icons={inspect:Search,focus:Focus,probe:MousePointer2};
function load(){try{const d=JSON.parse(localStorage.getItem('ux-crime-scene:v1')||'{}');return Array.isArray(d.completed)?d.completed.filter((n:unknown)=>typeof n==='number'&&n>=1&&n<=3):[]}catch{return []}}
function App(){
 const [completed,setCompleted]=useState<number[]>(load),[level,setLevel]=useState(0),[tool,setTool]=useState<Tool>('inspect'),[vision,setVision]=useState(false),[wheel,setWheel]=useState(false),[dossier,setDossier]=useState(false),[mode,setMode]=useState<'use'|'investigate'>('use'),[selected,setSelected]=useState(''),[triggers,setTriggers]=useState<string[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]),[solved,setSolved]=useState<string[]>([]),[falseCount,setFalseCount]=useState(0),[journey,setJourney]=useState(false),[notice,setNotice]=useState(''),[category,setCategory]=useState(categories[0]),[activeEvidence,setActiveEvidence]=useState(''),[sound,setSound]=useState(false),[closed,setClosed]=useState(false),[elapsed,setElapsed]=useState(0),[offset,setOffset]=useState({x:0,y:0});
 const c=cases[level],timer=useRef<ReturnType<typeof setTimeout>|null>(null),pendingTimer=useRef<ReturnType<typeof setTimeout>|null>(null),start=useRef(Date.now()),focusTrail=useRef<string[]>([]),audioRef=useRef<AudioContext|null>(null);
 const mark=(t:string)=>setTriggers(p=>p.includes(t)?p:[...p,t]);
 function beep(){if(!sound)return;try{const a=audioRef.current??(audioRef.current=new AudioContext());void a.resume();const o=a.createOscillator(),g=a.createGain();o.connect(g);g.connect(a.destination);o.frequency.value=660;g.gain.setValueAtTime(.04,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.15);o.start();o.stop(a.currentTime+.15)}catch{}}
 function reset(n:number){if(timer.current)clearTimeout(timer.current);if(pendingTimer.current)clearTimeout(pendingTimer.current);timer.current=null;pendingTimer.current=null;setLevel(n);setTool('inspect');setSelected('');setTriggers([]);setEvidence([]);setSolved([]);setFalseCount(0);setJourney(false);setClosed(false);setActiveEvidence('');setMode('use');setNotice('');setOffset({x:0,y:0});setVision(false);setElapsed(0);setWheel(false);setDossier(false);focusTrail.current=[];start.current=Date.now()}
 useEffect(()=>{try{localStorage.setItem('ux-crime-scene:v1',JSON.stringify({completed}))}catch{setNotice('El navegador no permite guardar el progreso. Esta sesión sigue funcionando.')}},[completed]);
 useEffect(()=>{const t=setInterval(()=>{if(!closed)setElapsed(Math.floor((Date.now()-start.current)/1000))},1000);return()=>clearInterval(t)},[closed]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(pendingTimer.current)clearTimeout(pendingTimer.current);void audioRef.current?.close()},[]);
 useEffect(()=>{function key(e:KeyboardEvent){const el=e.target as HTMLElement;if(el.closest('input,textarea,select,[contenteditable="true"]'))return;if(e.key==='Escape'){e.preventDefault();if(wheel)setWheel(false);else setDossier(v=>!v)}if(e.key.toLowerCase()==='q'){e.preventDefault();setWheel(v=>!v)}if(mode==='investigate'){if(e.code==='Space'){e.preventDefault();setVision(v=>!v)}if(['1','2','3'].includes(e.key)){const t=c.tools[Number(e.key)-1];if(t)setTool(t)}if(e.key.toLowerCase()==='e'&&selected){e.preventDefault();capture()}const moves:Record<string,[number,number]>={w:[0,24],ArrowUp:[0,24],s:[0,-24],ArrowDown:[0,-24],a:[24,0],ArrowLeft:[24,0],d:[-24,0],ArrowRight:[-24,0]};if(moves[e.key]){e.preventDefault();const [x,y]=moves[e.key];setOffset(p=>({x:Math.max(-160,Math.min(160,p.x+x)),y:Math.max(-120,Math.min(120,p.y+y))}))}}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)});
 useEffect(()=>{if(!wheel&&!dossier&&!closed)return;const previous=document.activeElement as HTMLElement;const dialog=document.querySelector<HTMLElement>('[role=dialog]');function trap(e:KeyboardEvent){if(e.key!=='Tab'||!dialog)return;const nodes=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),a,input,select,[tabindex="0"]'));const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}document.addEventListener('keydown',trap);return()=>{document.removeEventListener('keydown',trap);previous?.focus()}},[wheel,dossier,closed]);
 function capture(){if(!selected)return;const obs=observe(c,selected,tool,triggers);if(evidence.some(e=>e.suspect===selected&&e.observation===obs.observation)){setNotice('Esta observación ya está registrada.');return}const item={...obs,id:crypto.randomUUID()};setEvidence(p=>[...p,item]);setActiveEvidence(item.id);setNotice('Evidencia archivada. Relaciónala con una acusación.');beep()}
 function accuse(){const e=evidence.find(e=>e.id===activeEvidence);if(!e)return;const result=evaluate(c,e,category,solved);if(result==='correct'){setSolved(p=>[...p,e.crimeId!]);setNotice('Acusación confirmada · +250 XP');beep()}else if(result==='duplicate')setNotice('Este problema ya está demostrado.');else{setFalseCount(p=>p+1);setNotice('Acusación sin fundamento · −75 XP. Revisa la prueba y su contexto.')}}
 function select(e:React.MouseEvent,s:string){if(mode==='investigate'){e.preventDefault();e.stopPropagation();setSelected(s)}}
 function focused(s:string){focusTrail.current.push(s);if(focusTrail.current.slice(-3).join(',')==='address,city,postal')mark('focus-seen')}
 const suspect=(s:string)=>({'data-suspect':s,tabIndex:mode==='investigate'?0:undefined,role:mode==='investigate'?'button':undefined,'aria-label':mode==='investigate'?`Inspeccionar ${c.suspects[s]}`:undefined,onKeyDown:(e:React.KeyboardEvent)=>{if(mode==='investigate'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopPropagation();setSelected(s)}},onClickCapture:(e:React.MouseEvent)=>select(e,s),className:`suspect ${selected===s&&mode==='investigate'?'selected':''}`});
 function finish(){if(!journey||solved.length<c.crimes.length)return;setClosed(true);setCompleted(p=>p.includes(c.id)?p:[...p,c.id]);beep()}
 const observation=selected?observe(c,selected,tool,triggers):null;
 return <div className="app"><aside className="rail"><a className="logo" href="#" aria-label="UX Crime Scene"><Fingerprint size={29}/></a><span className="rail-line"/><button className="rail-button active" aria-label="Investigación" onClick={()=>setDossier(false)}><Scan/></button><button className="rail-button" aria-label="Abrir expediente" onClick={()=>setDossier(true)}><FolderOpen/></button><div className="rail-bottom"><button className="rail-button" onClick={()=>setSound(v=>!v)} aria-label={sound?'Desactivar sonido':'Activar sonido'}>{sound?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><span className="avatar">JD</span></div></aside>
 <div className="shell"><header><div className="brand">UX CRIME SCENE<span>BUREAU OF INTERFACE INVESTIGATION</span></div><div className="header-right"><span className="status-dot"/> SISTEMA EN LÍNEA <span className="divider"/> <span className="agent">DETECTIVE <b>J. DOE</b></span></div></header>
 <main><div className="breadcrumb">ARCHIVO DE CASOS <ChevronRight size={12}/> INVESTIGACIÓN ACTIVA</div><div className="heading"><div><div className="eyebrow">EXPEDIENTE / 00{c.id} <span className="tag">NIVEL {c.id} · {['INICIACIÓN','INTERMEDIO','AVANZADO'][level]}</span></div><h1>{c.title}<span>.</span></h1><p>La interfaz guarda secretos. Encuentra las pruebas.</p></div><button className="outline dossier-btn" onClick={()=>setDossier(true)}><FolderOpen size={16}/> Abrir expediente <kbd>ESC</kbd></button></div>
 <div className="case-tabs">{cases.map((v,i)=><button key={v.id} className={i===level?'current':''} disabled={i>0&&!completed.includes(i)} onClick={()=>reset(i)}><span className="tab-number">{completed.includes(v.id)?<Check size={14}/>:i>0&&!completed.includes(i)?<Lock size={12}/>:String(v.id).padStart(2,'0')}</span>{['Registro','Formulario','Checkout'][i]}<span className="tab-desc">{['Aprende a observar','Sigue el recorrido','Conecta las pruebas'][i]}</span>{i===level&&<span className="live-dot"/>}</button>)}</div>
 <div className="workspace"><section className="scene-panel"><div className="panel-top"><span><span className="status-dot"/> ESCENA INTERACTIVA</span><span className="muted mono">{c.victim.toUpperCase()} / SANDBOX</span></div><div className="mission"><Target size={19}/><div><span>OBJETIVO DEL USUARIO</span><p>{c.mission}</p></div><span className={`mission-status ${journey?'done':''}`}>{journey?'COMPLETADO':'EN CURSO'}</span></div>
 <div className="scene-toolbar"><div className="segmented"><button className={mode==='use'?'on':''} onClick={()=>setMode('use')}><MousePointer2 size={13}/> Usar interfaz</button><button className={mode==='investigate'?'on':''} onClick={()=>setMode('investigate')}><Search size={13}/> Investigar</button></div><button className={`vision-toggle ${vision?'enabled':''}`} onClick={()=>setVision(v=>!v)}><Scan size={14}/> Visión forense <kbd>␣</kbd></button></div>
 <div className={`scene ${vision?'forensic':''} ${mode==='investigate'?'investigating':''}`}><div className="scene-grid"/><div className="browser" style={{transform:`translate(${offset.x}px,${offset.y}px)`}} key={level}><div className="browser-bar"><div className="traffic"><i/><i/><i/></div><span><Lock size={10}/> {c.victim.toLowerCase()}.example/{level===0?'signup':level===1?'delivery':'checkout'}</span><span>•••</span></div>
 <div className="fake-site"><div className="fake-brand">{c.victim.toLowerCase()}<span>®</span></div>
 {level===0&&<><h2>Tu próxima idea<br/>empieza aquí.</h2><p className="fake-intro">Únete a un espacio para crear algo diferente.</p><form onSubmit={e=>{e.preventDefault();if(mode==='investigate')return;const d=new FormData(e.currentTarget);if(String(d.get('password')).length<8){mark('register-error');setNotice('Registro rechazado. Observa el estado de la contraseña.')}else{setJourney(true);setNotice('Cuenta creada. Ahora investiga la interfaz.')}}}><label {...suspect('name')}>Nombre<input name="name" aria-label="Nombre" placeholder="Tu nombre" required readOnly={mode==='investigate'}/></label><div {...suspect('email')}><input name="email" type="email" placeholder="Correo electrónico" required readOnly={mode==='investigate'}/></div><label {...suspect('password')}>Contraseña<input name="password" type="password" aria-label="Contraseña" placeholder="Crea una contraseña" required readOnly={mode==='investigate'}/>{triggers.includes('register-error')&&<small className="fake-error">Usa al menos 8 caracteres.</small>}</label><div {...suspect('submit')}><button className="fake-primary" type="submit">Crear cuenta <ArrowRight size={15}/></button></div></form><div {...suspect('badge')} className="fake-foot suspect"><ShieldCheck size={13}/> Gratis. Sin tarjeta de crédito.</div></>}
 {level===1&&<><h2>¿Dónde lo enviamos?</h2><p className="fake-intro">Tu paquete está a un paso de casa.</p><form onSubmit={e=>{e.preventDefault();if(mode==='investigate')return;const d=new FormData(e.currentTarget);if(!/^\d{5}$/.test(String(d.get('postal')))){mark('delivery-error');setNotice('El envío no se confirmó. Examina el formulario.')}else{setJourney(true);setNotice('Dirección confirmada. Completa la investigación.')}}}><label {...suspect('address')}>Dirección<input name="address" tabIndex={1} onFocus={()=>focused('address')} placeholder="Calle y número" required readOnly={mode==='investigate'}/></label><div className="form-row"><label {...suspect('postal')}>Código postal<input name="postal" tabIndex={3} onFocus={()=>focused('postal')} className={triggers.includes('delivery-error')?'color-error':''} placeholder="28001" required readOnly={mode==='investigate'}/></label><label {...suspect('city')}>Ciudad<input name="city" tabIndex={2} onFocus={()=>focused('city')} placeholder="Madrid" required readOnly={mode==='investigate'}/></label></div><div {...suspect('submit')}><button className="fake-primary" type="submit">Confirmar envío <ArrowRight size={15}/></button></div></form><div {...suspect('badge')} className="fake-foot suspect"><ShieldCheck size={13}/> Envío estándar · 3–5 días</div></>}
 {level===2&&<><h2>Un último paso.</h2><p className="fake-intro">Una buena luz cambia todo.</p><div className="product"><div className="lamp"><div/><span/></div><div><b>Lámpara Atelier</b><span>Salvia / Edición de estudio</span></div><b>49,00 €</b></div><label {...suspect('promo')}>Código promocional<input placeholder="¿Tienes un código?" readOnly={mode==='investigate'}/></label><label {...suspect('terms')} className={`consent suspect ${selected==='terms'?'selected':''}`}><input type="checkbox" defaultChecked readOnly={mode==='investigate'}/> Quiero recibir novedades y ofertas por email.</label><div className="total"><span>Total · envío incluido</span><b>49,00 €</b></div><div {...suspect('pay')}><button className="fake-primary" disabled={journey} onClick={()=>{if(mode==='investigate'||journey||timer.current)return;pendingTimer.current=setTimeout(()=>mark('payment-pending'),2100);timer.current=setTimeout(()=>{setJourney(true);timer.current=null;setNotice('Pedido confirmado. ¿Qué ocurrió durante la espera?')},6500)}}> {journey?'Pedido confirmado':'Pagar pedido'} <ArrowRight size={15}/></button></div><div {...suspect('badge')} className="fake-foot suspect"><ShieldCheck size={13}/> Pago cifrado y seguro</div></>}
 </div></div><span className="scene-corner">FIG. 0{c.id} — INTERFAZ BAJO INVESTIGACIÓN</span>{vision&&<span className="vision-label"><Scan size={12}/> FORENSIC VISION ACTIVE</span>}</div>
 <div className="scene-footer"><span><MousePointer2 size={13}/> {mode==='use'?'Interactúa como usuario. Después cambia a Investigar.':'Selecciona un elemento y captura lo que observas.'}</span><span><kbd>WASD</kbd> explorar <kbd>E</kbd> capturar</span></div></section>
 <aside className="investigation"><div className="panel-top"><span>ESTADO DEL CASO</span><Fingerprint size={16}/></div><div className="case-summary"><span className="eyebrow">VÍCTIMA</span><h3>{c.victim}</h3><p>{c.incident}</p><div className="stats"><div><strong>{solved.length}<span>/{c.crimes.length}</span></strong><small>CRIMES RESUELTOS</small></div><div><strong>{String(evidence.length).padStart(2,'0')}</strong><small>EVIDENCIAS</small></div></div><div className="progress"><i style={{width:`${solved.length/c.crimes.length*100}%`}}/></div></div>
 <div className="tool-section"><div className="section-title">KIT DE INVESTIGACIÓN <button onClick={()=>setWheel(true)} aria-label="Abrir rueda de herramientas"><kbd>Q</kbd></button></div><div className="tools">{c.tools.map((t,i)=>{const Icon=icons[t];return <button key={t} className={tool===t?'chosen':''} onClick={()=>{setTool(t);setMode('investigate')}}><Icon size={18}/><span>{toolNames[t]}</span><kbd>{i+1}</kbd></button>})}</div></div>
 <div className="observation"><div className="section-title">OBSERVACIÓN <span className="mini-dot"/></div>{selected?<><span className="selected-label">{c.suspects[selected]}</span><p>{observation?.observation}</p><button className="capture" onClick={capture}><Camera size={15}/> Capturar evidencia <kbd>E</kbd></button></>:<div className="empty-observation"><Search size={26}/><p>Todo empieza con<br/>una buena observación.</p><span>Activa Investigar y selecciona un elemento.</span></div>}</div>
 </aside></div>
 <div className="bottom-grid"><section className="evidence-panel"><div className="section-title">BANDEJA DE EVIDENCIAS <span>{String(evidence.length).padStart(2,'0')} ARCHIVADAS</span></div>{evidence.length===0?<div className="empty-evidence"><Camera size={19}/><p>Aún no hay pruebas. Usa tus herramientas para documentar lo que ocurre.</p></div>:<div className="evidence-list">{evidence.map((e,i)=><button key={e.id} className={e.id===activeEvidence?'picked':''} onClick={()=>{setActiveEvidence(e.id);setSelected(e.suspect)}}><span className="evidence-index">E{String(i+1).padStart(2,'0')}</span><div><b>{c.suspects[e.suspect]}</b><p>{e.observation}</p></div>{solved.includes(e.crimeId||'')?<CheckCircle2 size={17}/>:<ChevronRight size={16}/>}</button>)}</div>}{evidence.length>0&&<div className="accusation"><label htmlFor="category">Acusar con la prueba seleccionada</label><div><select id="category" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(t=><option key={t}>{t}</option>)}</select><button className="yellow" disabled={!activeEvidence} onClick={accuse}>Presentar <ArrowUpRight size={15}/></button></div></div>}</section><section className="field-notes"><div className="section-title">NOTAS DE CAMPO <span>0{c.id} / GUÍA</span></div><span className="note-number">{['01','02','03'][level]}</span><h3>{['Observa antes de acusar.','Los errores dejan huellas.','El silencio también es una pista.'][level]}</h3><p>{['Prueba primero una contraseña corta. Después completa el registro. Inspecciona el correo y la contraseña en sus distintos estados.','Envía un código postal inválido. Para estudiar el foco, selecciona Focus tracker, vuelve a Usar interfaz, enfoca Dirección y pulsa Tab dos veces.','Examina las opciones iniciales. Activa Interaction probe y paga en modo Uso; cambia a Investigar durante la espera para capturar lo observado.'][level]}</p><div className="note-foot"><span>EXPLORAR ES GRATIS.</span> ACUSAR REQUIERE PRUEBAS.</div></section></div>
 <div className="notice" role="status">{notice||'Tu misión: completar el recorrido y demostrar los dos problemas del caso.'}</div><footer><span><span className="status-dot"/> PROGRESO GUARDADO EN ESTE DISPOSITIVO</span><div><span>{Math.max(0,solved.length*250-falseCount*75)} XP</span><span>{String(Math.floor(elapsed/60)).padStart(2,'0')}:{String(elapsed%60).padStart(2,'0')}</span><button className="yellow" disabled={!journey||solved.length<c.crimes.length} onClick={finish}>Cerrar caso <ArrowUpRight size={15}/></button></div></footer>
 </main></div>
 {wheel&&<div className="modal-backdrop" onClick={()=>setWheel(false)}><section className="modal wheel" role="dialog" aria-modal="true" aria-label="Herramientas" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setWheel(false)} aria-label="Cerrar"><X/></button><span className="eyebrow">EQUIPAMIENTO</span><h2>Elige tu herramienta.</h2><div>{c.tools.map(t=>{const Icon=icons[t];return <button key={t} onClick={()=>{setTool(t);setMode('investigate');setWheel(false)}}><Icon size={30}/><b>{toolNames[t]}</b><span>{t==='inspect'?'Examina propiedades y estados':t==='focus'?'Registra el recorrido del teclado':'Analiza la respuesta a una acción'}</span></button>})}</div></section></div>}
 {dossier&&<div className="modal-backdrop" onClick={()=>setDossier(false)}><section className="modal" role="dialog" aria-modal="true" aria-label="Expediente" onClick={e=>e.stopPropagation()}><button className="close" autoFocus onClick={()=>setDossier(false)} aria-label="Cerrar"><X/></button><span className="eyebrow">CONFIDENCIAL / CASE 00{c.id}</span><h2>{c.title}</h2><p>{c.incident}. {c.mission}</p><h3>Sospechosos</h3><div className="suspect-tags">{Object.entries(c.suspects).map(([id,name])=><button key={id} onClick={()=>{setSelected(id);setMode('investigate');setDossier(false)}}>{name}<ArrowUpRight size={12}/></button>)}</div><h3>Conclusiones demostradas</h3>{solved.length?c.crimes.filter(x=>solved.includes(x.id)).map(x=><div className="debrief" key={x.id}><b><Check size={15}/> {x.category}</b><p>{x.explanation}</p></div>):<p>Todavía no hay conclusiones. Reúne evidencia antes de acusar.</p>}<p className="muted">Las interfaces y sus datos son ficticios. No uses información personal.</p><button className="outline" onClick={()=>reset(level)}><RotateCcw size={14}/> Reiniciar este caso</button></section></div>}
 {closed&&<div className="modal-backdrop"><section className="modal closed" role="dialog" aria-modal="true" aria-label="Caso cerrado"><span className="stamp">CASE CLOSED</span><span className="eyebrow">EXPEDIENTE 00{c.id} / RESUELTO</span><h2>Buen trabajo, detective.</h2><p>Completaste el recorrido y demostraste {solved.length} problemas.</p><div className="result-stats"><div><b>{Math.round(solved.length/(solved.length+falseCount)*100)}%</b><span>PRECISIÓN</span></div><div><b>{falseCount}</b><span>ACUSACIONES FALSAS</span></div><div><b>{Math.max(0,solved.length*250-falseCount*75)}</b><span>XP</span></div></div>{c.crimes.map(x=><div className="debrief" key={x.id}><b><CheckCircle2 size={16}/>{x.category}</b><p>{x.explanation}</p></div>)}<button className="yellow" autoFocus onClick={()=>level<2?reset(level+1):reset(0)}>{level<2?'Abrir siguiente caso':'Volver al primer caso'}<ArrowRight size={16}/></button><button className="text-button" onClick={()=>{setClosed(false);setDossier(true)}}><ChevronLeft size={13}/> Revisar expediente</button></section></div>}
 </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
